name: atkbench
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - matplotlib=3.5.1
  - pip=21.2.4
  - python=3.9
  - pytorch=1.11
  - torchvision=0.12
  - cleverhans=4.0.0
  - pip:
    - h5py==3.8.0
    - adversarial-robustness-toolbox==1.13.1
    - foolbox==3.3.3
    - git+https://github.com/RobustBench/robustbench.git
    - git+https://github.com/jeromerony/adversarial-library.git
    - deeprobust==0.2.5
    - pandas==1.3.5
    - sacred==0.8.4
    - scipy<1.8.0
    - torchattacks==3.3.0
    - tqdm==4.56.2
    - wget==3.2

