name: atkbench
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.3
  - matplotlib=3.5.1
  - pip=21.2.4
  - python=3.9
  - python=3.9.12
  - pytorch=1.11
  - torchvision=0.12
  - pip:
    - adversarial-robustness-toolbox==1.10.2
    - foolbox==3.3.3
    - git+https://github.com/RobustBench/robustbench.git
    - git+https://github.com/jeromerony/adversarial-library.git
    - pandas==1.2.5
    - sacred==0.8.2
    - torchattacks==3.2.6
    - tqdm==4.56.2