name: atkbench
channels:
  - soumith
  - defaults
dependencies:
  - matplotlib=3.5.1
  - python=3.9.12
  - pip==21.2.4
  - pip:
    - git+https://github.com/jeromerony/adversarial-library.git
    - foolbox==3.3.3
    - geotorch==0.3.0
    - numpy==1.22.3
    - pandas==1.2.5
    - git+https://github.com/RobustBench/robustbench.git
    - sacred==0.8.2
    - scipy==1.8.0
    - torch==1.11.0
    - torchvision==0.12.0
    - tqdm==4.56.2
    - torchattacks==3.2.6